---
development:
  music_directory: c:\media\music
  movie_directory: c:\media\movies
  organize: true
test:
  music_directory: c:\Music
  movie_directory: c:\Movies
  organize: true
production:
  music_directory: c:\Music
  movie_directory: c:\Movies
  organize: true
